OPENAI_API_KEY= "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"
OPEN_API_KEY= "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"
api_key = "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"