# OPENAI_API_KEY= "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"
# OPEN_API_KEY= "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"
# api_key = "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"
OPENAI_API_KEY= "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"
OPEN_API_KEY= "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"
api_key = "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"
